### ISSUE TITLE
Remove common service 

### ISSUE THREAD

**Issue by the-jake-z** [UA-ACM-Student-Chapter/ACMWebUtil#18]
- Common service name does not reflect any specific kind of functionality (except as a bucket for a bunch of code)
- [Handling Errors](http://www.baeldung.com/exception-handling-for-rest-with-spring)
- [Request Handlers](https://www.tuturself.com/posts/view?menuId=3&postId=1071)

https://github.com/UA-ACM-Student-Chapter/ACMWebUtil/blob/166483322dab008445b89bd4ed2f5d25acc25c10/src/main/java/edu/ua/cs/acm/services/CommonService.java#L9

**Comment by david-shortman** [comment]
good point. we should probably investigate how to properly create a response object and return as json instead of the makeshift solution. at least for now, i could rename the service to RequestService...

**Comment by david-shortman** [comment]
@asa-dillahunty can I be unassaigned and this issue closed? I'm assuming students will want to write a new service rather than maintaining this mess I made 😅.

**Comment by asa-dillahunty** [comment]
Sure thing!
