### ISSUE TITLE
Add swagger for actual api documentation

### ISSUE THREAD

**Issue by the-jake-z** [UA-ACM-Student-Chapter/ACMWebUtil#19]
Use this to have auto-updating API docs:

http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

**Comment by david-shortman** [comment]
will def investigate. thanks!

**Comment by david-shortman** [comment]
@asa-dillahunty can I be unassaigned and this issue closed? I'm assuming students will want to write a new service rather than maintaining this mess I made 😅.

**Comment by asa-dillahunty** [comment]
Of course, sorry about that!
